version: 2
updates:
  # 1) Poetry-managed dependencies: sees only pyproject.toml + poetry.lock
  - package-ecosystem: pip
    directory: "/"            # root only has pyproject.toml + poetry.lock
    schedule:
      interval: weekly
