version: 2
updates:
  # 1) Poetry-managed dependencies: sees only pyproject.toml + poetry.lock
  - package-ecosystem: pip
    directory: "/"            # root only has pyproject.toml + poetry.lock
    schedule:
      interval: daily

  # 2) requirements.txt-only updates: sees only the .txt
  - package-ecosystem: pip
    directory: "/reqs"        # move requirements.txt → reqs/requirements.txt
    schedule:
      interval: daily
